### ISSUE TITLE
Test it on mac

### ISSUE THREAD

**Issue by MikeKovarik** [MikeKovarik/rollup-plugin-notify#2]
node-notifier isn't the most reliable and getting it to work required a little hack. But that was tailored to and tested on Windows only. I'd love to test the plugin (and fix potential problems) on mac, but i don't have any around me atm.

**Comment by rob-marr** [comment]
I've been using this extensively on mac for a few weeks and as you can see from the screenshot it works great. 

<img width="170" alt="Screen Shot 2019-09-07 at 12 57 03" src="https://user-images.githubusercontent.com/48574850/64474616-07908e80-d16f-11e9-8080-0f305695b1ba.png">

**Comment by MikeKovarik** [comment]
awesome, thank you :)

**Comment by rob-marr** [comment]
No problem, thanks for the plugin.👍🏻
